---
# configure nrpe on the server

- name: Add config on server
  template: src=nrpe-hosts.cfg.j2 dest=/etc/nagios3/conf.d/{{ client_name_short }}-hosts.cfg owner=root mode=0755

- name: New config section on server
  template: src=nrpe-server.cfg.j2 dest=/etc/nagios-plugins/config/check_nrpe_{{ client_name_short }}.cfg owner=root mode=0755
  notify: Restart nagios3 service
